CREATE TABLE [dbo].[COM_CUSTOMER] (
    [COM_CUSTOMER_ID] INT           NOT NULL,
    [CUSTOMER_NAME]   VARCHAR (100) NULL,
    CONSTRAINT [PK_COM_CUSTOMER] PRIMARY KEY CLUSTERED ([COM_CUSTOMER_ID] ASC)
);

