


using System;
using System.Diagnostics;
using System.Collections;
using System.Data;
using System.Data.SqlClient;
using System.Xml.Serialization;
using PFSHelper.DataAccessLayer;

#region Region: Revision History///////////////////////////////////////////////////////////////
// Copyright (c) 2011, PT. Profescipta Wahanatehnik. All Rights Reserved.
//
// This software, all associated documentation, and all copies
// are CONFIDENTIAL INFORMATION of PT. Profescipta Wahanatehnik. 
// http://www.profescipta.com
//
// $Workfile:$
// $Revision:$
// $Date:$
//
// DESCRIPTION
//
// $Log:$
//
#endregion

namespace PFSHelper.BusinessLogicLayer
{
	//Standard class autogenerated by PFS Generator v5.0
	public partial class ModuleObjectMemberGroup
	{
		#region Region: Member Variables///////////////////////////////////////////////////////////
		protected int m_iModuleObjectMemberGroupID = 0;
		protected int m_iModuleID = 0;
        protected string m_sModuleCode = "NONE";
        protected string m_sModuleName = "NONE";
		protected int m_iModuleObjectID = 0;
        protected string m_sObjectCode = "NONE";
        protected string m_sObjectName = "NONE";
		protected int m_iModuleObjectMemberID = 0;
        protected string m_sMemberCode = "NONE";
        protected string m_sMemberName = "NONE";
		protected int m_iGroupID = 0;
		protected string m_sGroupName = "NONE";
		#endregion
		
		#region Region: Constructor////////////////////////////////////////////////////////////////
		public ModuleObjectMemberGroup()
		{
			m_iModuleObjectMemberGroupID = -1;
		}	
		public ModuleObjectMemberGroup(int iID)
		{
			m_iModuleObjectMemberGroupID = iID;
		}

		public ModuleObjectMemberGroup(
			int iModuleObjectMemberGroupID,
			int iModuleID,
			int iModuleObjectID,
			int iModuleObjectMemberID,
			int iGroupID
			)
		{
			m_iModuleObjectMemberGroupID = iModuleObjectMemberGroupID;
			m_iModuleID = iModuleID;
			m_iModuleObjectID = iModuleObjectID;
			m_iModuleObjectMemberID = iModuleObjectMemberID;
			m_iGroupID = iGroupID;
		}

		#endregion
		
		#region Region: Properties/////////////////////////////////////////////////////////////////
		
		public int ModuleObjectMemberGroupID
		{
			get {return m_iModuleObjectMemberGroupID;}
			set {m_iModuleObjectMemberGroupID = value;}
		}

		public int ModuleID
		{
			get {return m_iModuleID;}
			set {m_iModuleID = value;}
		}

        public string ModuleCode
        {
            get { return m_sModuleCode; }
            set { m_sModuleCode = value; }
        }

        public string ModuleName
        {
            get { return m_sModuleName; }
            set { m_sModuleName = value; }
        }

		public int ModuleObjectID
		{
			get {return m_iModuleObjectID;}
			set {m_iModuleObjectID = value;}
		}

        public string ObjectCode
        {
            get { return m_sObjectCode; }
            set { m_sObjectCode = value; }
        }

        public string ObjectName
        {
            get { return m_sObjectName; }
            set { m_sObjectName = value; }
        }

		public int ModuleObjectMemberID
		{
			get {return m_iModuleObjectMemberID;}
			set {m_iModuleObjectMemberID = value;}
		}

        public string MemberCode
        {
            get { return m_sMemberCode; }
            set { m_sMemberCode = value; }
        }

        public string MemberName
        {
            get { return m_sMemberName; }
            set { m_sMemberName = value; }
        }

		public int GroupID
		{
			get {return m_iGroupID;}
			set {m_iGroupID = value;}
		}

		public string GroupName
		{
			get {return m_sGroupName;}
			set {m_sGroupName = value;}
		}
		#endregion
		
		#region Region: Data Access Methods////////////////////////////////////////////////////////
		public bool DAL_Load()
        {
			bool bIsSuccess = false;
            try
            {
				using(SqlDataReader drModuleObjectMemberGroup = SqlHelper.ExecuteReader(PFSHelper.DataAccessLayer.PFSDataBaseAccess.ConnectionString, "uspPFS_ModuleObjectMemberGroupGet", m_iModuleObjectMemberGroupID))
            	{
					if(drModuleObjectMemberGroup.Read())
            		{      
						m_iModuleObjectMemberGroupID = Convert.ToInt32(drModuleObjectMemberGroup["PFS_MODULE_OBJECT_MEMBER_GROUP_ID"]);
						m_iModuleID = Convert.ToInt32(drModuleObjectMemberGroup["PFS_MODULE_ID"]);
						m_iModuleObjectID = Convert.ToInt32(drModuleObjectMemberGroup["PFS_MODULE_OBJECT_ID"]);
						m_iModuleObjectMemberID = Convert.ToInt32(drModuleObjectMemberGroup["PFS_MODULE_OBJECT_MEMBER_ID"]);
						m_iGroupID = Convert.ToInt32(drModuleObjectMemberGroup["PFS_GROUP_ID"]);
						m_sModuleCode = Convert.ToString(drModuleObjectMemberGroup["MODULE_CODE"]);
						m_sModuleName = Convert.ToString(drModuleObjectMemberGroup["MODULE_NAME"]);
						m_sObjectCode = Convert.ToString(drModuleObjectMemberGroup["OBJECT_CODE"]);
						m_sObjectName = Convert.ToString(drModuleObjectMemberGroup["OBJECT_NAME"]);
						m_sMemberCode = Convert.ToString(drModuleObjectMemberGroup["MEMBER_CODE"]);
						m_sMemberName = Convert.ToString(drModuleObjectMemberGroup["MEMBER_NAME"]);
						m_sGroupName = Convert.ToString(drModuleObjectMemberGroup["GROUP_NAME"]);
						bIsSuccess = true;
           		 	}
            	}
				return bIsSuccess;
			}
			catch(Exception ex)
			{
				throw ex;
			}
        }	
		
		public bool DAL_Load(int iID)
        {
			bool bIsSuccess = false;
            try
            {
				using(SqlDataReader drModuleObjectMemberGroup = SqlHelper.ExecuteReader(PFSHelper.DataAccessLayer.PFSDataBaseAccess.ConnectionString, "uspPFS_ModuleObjectMemberGroupGet",iID))
            	{
					if(drModuleObjectMemberGroup.Read())
            		{      
						m_iModuleObjectMemberGroupID = Convert.ToInt32(drModuleObjectMemberGroup["PFS_MODULE_OBJECT_MEMBER_GROUP_ID"]);
						m_iModuleID = Convert.ToInt32(drModuleObjectMemberGroup["PFS_MODULE_ID"]);
						m_iModuleObjectID = Convert.ToInt32(drModuleObjectMemberGroup["PFS_MODULE_OBJECT_ID"]);
						m_iModuleObjectMemberID = Convert.ToInt32(drModuleObjectMemberGroup["PFS_MODULE_OBJECT_MEMBER_ID"]);
						m_iGroupID = Convert.ToInt32(drModuleObjectMemberGroup["PFS_GROUP_ID"]);
						m_sModuleCode = Convert.ToString(drModuleObjectMemberGroup["MODULE_CODE"]);
						m_sModuleName = Convert.ToString(drModuleObjectMemberGroup["MODULE_NAME"]);
						m_sObjectCode = Convert.ToString(drModuleObjectMemberGroup["OBJECT_CODE"]);
						m_sObjectName = Convert.ToString(drModuleObjectMemberGroup["OBJECT_NAME"]);
						m_sMemberCode = Convert.ToString(drModuleObjectMemberGroup["MEMBER_CODE"]);
						m_sMemberName = Convert.ToString(drModuleObjectMemberGroup["MEMBER_NAME"]);
						m_sGroupName = Convert.ToString(drModuleObjectMemberGroup["GROUP_NAME"]);
						bIsSuccess = true;
           		 	}
            	}
				return bIsSuccess;
			}
			catch(Exception ex)
			{
				throw ex;
			}
        }
		
		public bool DAL_Update() 
		{
			SqlConnection oConn = PFSDataBaseAccess.OpenConnection();
            SqlTransaction oTrans = oConn.BeginTransaction();
			try
			{
				bool bIsSuccess = false;
				bIsSuccess = DAL_Update(oTrans);
				if (!bIsSuccess)
                {
                    oTrans.Rollback();
                    return false;
                }
				
				oTrans.Commit();
                return true;
			}
			catch (SqlException ex)
            {
                oTrans.Rollback();
                throw (ex);
            }
            finally
            {
                PFSDataBaseAccess.CloseConnection(ref oConn);
            }
		}		
		public bool DAL_Update(SqlTransaction p_oTrans) 
		{
			try
			{
				bool bIsSuccess = false;
				if (m_iModuleObjectMemberGroupID > 0)
				{
					int iError = Convert.ToInt32(SqlHelper.ExecuteScalar(p_oTrans, "uspPFS_ModuleObjectMemberGroupUpdate",
					m_iModuleObjectMemberGroupID,
										m_iModuleID,
										m_iModuleObjectID,
										m_iModuleObjectMemberID,
										m_iGroupID
					));
					bIsSuccess = (iError == 0);
				}
				else
				{
					bIsSuccess = DAL_Add(p_oTrans);
				}			
				return (bIsSuccess);
			}
			catch (Exception ex)
			{
                throw ex;
			}
		}
		
		
		public bool DAL_Delete() 
        {
            SqlConnection oConn = PFSDataBaseAccess.OpenConnection();
            SqlTransaction oTrans = oConn.BeginTransaction();
            try
            {
                bool bIsSuccess = DAL_Delete(oTrans);

                if (!bIsSuccess)
                {
                    oTrans.Rollback();
                    return false;
                }

                oTrans.Commit();
                return true;
            }
            catch (SqlException ex)
            {
                oTrans.Rollback();
                throw (ex);
            }
            finally
            {
                PFSDataBaseAccess.CloseConnection(ref oConn);
            }
        }
        public bool DAL_Delete(SqlTransaction p_oTrans) 
        {
            try
            {
										
                int iRowAffected = SqlHelper.ExecuteNonQuery(p_oTrans, "uspPFS_ModuleObjectMemberGroupDelete", m_iModuleObjectMemberGroupID);

                return (iRowAffected > 0);
            }
            catch (SqlException ex)
            {
                throw (ex);
            }
        }	
        
		public bool DAL_Add() 
        {
            SqlConnection oConn = PFSDataBaseAccess.OpenConnection();
            SqlTransaction oTrans = oConn.BeginTransaction();
            try
            {
                bool bIsSuccess = DAL_Add(oTrans);

                if (!bIsSuccess)
                {
                    oTrans.Rollback();
                    return false;
                }

                oTrans.Commit();
                return true;
            }
            catch (SqlException ex)
            {
                oTrans.Rollback();
                throw (ex);
            }
            finally
            {
                PFSDataBaseAccess.CloseConnection(ref oConn);
            }
        }
		public bool DAL_Add(SqlTransaction p_oTrans)
        {
            try
            {
                m_iModuleObjectMemberGroupID = Convert.ToInt32(SqlHelper.ExecuteScalar(p_oTrans, "uspPFS_ModuleObjectMemberGroupAdd", 

					m_iModuleID,
					m_iModuleObjectID,
					m_iModuleObjectMemberID,
					m_iGroupID
					));
					
				bool bIsSuccess = (m_iModuleObjectMemberGroupID >=0);
				
				
				return bIsSuccess;
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
		
		//*** This section is a temporary data access for combo, Radio Button etc. ToDo: Delete this and use the proper class definition
		public static SqlDataReader DAL_ModuleObjectMemberGroupModuleList()
		{
			try
			{
				SqlDataReader dr = SqlHelper.ExecuteReader(PFSHelper.DataAccessLayer.PFSDataBaseAccess.ConnectionString, "LOOKUP_uspPFS_ModuleObjectMemberGroupModuleList"); 
				return dr;
			}
			catch(Exception ex)
			{
				throw(ex);
			}			
		}		
		public static SqlDataReader DAL_ModuleObjectMemberGroupModuleObjectList()
		{
			try
			{
				SqlDataReader dr = SqlHelper.ExecuteReader(PFSHelper.DataAccessLayer.PFSDataBaseAccess.ConnectionString, "LOOKUP_uspPFS_ModuleObjectMemberGroupModuleObjectList"); 
				return dr;
			}
			catch(Exception ex)
			{
				throw(ex);
			}			
		}		
		public static SqlDataReader DAL_ModuleObjectMemberGroupModuleObjectMemberList()
		{
			try
			{
				SqlDataReader dr = SqlHelper.ExecuteReader(PFSHelper.DataAccessLayer.PFSDataBaseAccess.ConnectionString, "LOOKUP_uspPFS_ModuleObjectMemberGroupModuleObjectMemberList"); 
				return dr;
			}
			catch(Exception ex)
			{
				throw(ex);
			}			
		}		
		public static SqlDataReader DAL_ModuleObjectMemberGroupGroupList()
		{
			try
			{
				SqlDataReader dr = SqlHelper.ExecuteReader(PFSHelper.DataAccessLayer.PFSDataBaseAccess.ConnectionString, "LOOKUP_uspPFS_ModuleObjectMemberGroupGroupList"); 
				return dr;
			}
			catch(Exception ex)
			{
				throw(ex);
			}			
		}		
		#endregion
	} //** Class
} //** Name Space
