/***********************************************************************************************************************
   Copyright (c) 2015 PT Profescipta Wahanatehnik. All Rights Reserved.
   This software, all associated documentation, and all copies
   DESCRIPTION
	Name    		:	uspTMPT_SecondStagingPscRmwCipAdd
	Desc    		:	This store procedure is use to add TMPT_SECOND_STAGING_PSC_RMW_CIP
	Create Date 	:	23 Jan 2015		- Created By  : PFS Generator v5.1
	Modified Date 	:	            	- Modified By :
	Comments		:
	Sample Data 	:
***********************************************************************************************************************/
CREATE PROCEDURE dbo.uspTMPT_SecondStagingPscRmwCipAdd
(
	@iFileImportID INT,
	@sCif VARCHAR(15),
	@iCustomerID INT,
	@iCusID INT,
	@sCustomerDob VARCHAR(50),
	@iBranchID INT,
	@sBranchCode VARCHAR(30),
	@sBranchName VARCHAR(100),
	@iCustomerSegmentID INT,
	@iCustomerRiskRatingID INT,
	@sEducationName VARCHAR(100),
	@iRmID INT,
	@sP1Q1 VARCHAR(2),
	@sP1Q2 VARCHAR(2),
	@sP1Q3 VARCHAR(2),
	@sP1Q4 VARCHAR(2),
	@sP1Q5 VARCHAR(2),
	@sP1Q6 VARCHAR(2),
	@sP1Q7 VARCHAR(2),
	@bQ1Em BIT,
	@dQ2TotalAsset FLOAT,
	@dQ2TotalLiabilities FLOAT,
	@bQ31 BIT,
	@bQ32 BIT,
	@bQ33 BIT,
	@bQ34 BIT,
	@bQ35 BIT,
	@bQ36 BIT,
	@bQ37 BIT,
	@bQ38 BIT,
	@bQ39 BIT,
	@bQ310 BIT,
	@bQ311 BIT,
	@bQ312 BIT,
	@bQ313 BIT,
	@bQ41 BIT,
	@bQ42 BIT,
	@bQ43 BIT,
	@bQ44 BIT,
	@bQ45 BIT,
	@bQ46 BIT,
	@dQ5Ith FLOAT,
	@bQ61 BIT,
	@bQ62 BIT,
	@bQ63 BIT,
	@bQ64 BIT,
	@bQ65 BIT,
	@bQ66 BIT,
	@bIsValid BIT,
	@sInvalidRemark VARCHAR(500),
	@sCreateDate VARCHAR(50)
)
AS
BEGIN
	DECLARE @iSecondStagingPscRmwCipID INT
    
	INSERT INTO TMPT_SECOND_STAGING_PSC_RMW_CIP 
    ( 	
		psc_file_import_id,
		cif,
		com_customer_id,
		cus_id,
		customer_dob,
		com_branch_id,
		branch_code,
		branch_name,
		com_customer_segment_id,
		com_customer_risk_rating_id,
		education_name,
		com_rm_id,
		p1_q1,
		p1_q2,
		p1_q3,
		p1_q4,
		p1_q5,
		p1_q6,
		p1_q7,
		q1_em,
		q2_total_asset,
		q2_total_liabilities,
		q3_1,
		q3_2,
		q3_3,
		q3_4,
		q3_5,
		q3_6,
		q3_7,
		q3_8,
		q3_9,
		q3_10,
		q3_11,
		q3_12,
		q3_13,
		q4_1,
		q4_2,
		q4_3,
		q4_4,
		q4_5,
		q4_6,
		q5_ith,
		q6_1,
		q6_2,
		q6_3,
		q6_4,
		q6_5,
		q6_6,
		is_valid,
		invalid_remark,
		create_date
	)
	VALUES
	(
		@iFileImportID,
		@sCif,
		@iCustomerID,
		@iCusID,
		@sCustomerDob,
		@iBranchID,
		@sBranchCode,
		@sBranchName,
		@iCustomerSegmentID,
		@iCustomerRiskRatingID,
		@sEducationName,
		@iRmID,
		@sP1Q1,
		@sP1Q2,
		@sP1Q3,
		@sP1Q4,
		@sP1Q5,
		@sP1Q6,
		@sP1Q7,
		@bQ1Em,
		@dQ2TotalAsset,
		@dQ2TotalLiabilities,
		@bQ31,
		@bQ32,
		@bQ33,
		@bQ34,
		@bQ35,
		@bQ36,
		@bQ37,
		@bQ38,
		@bQ39,
		@bQ310,
		@bQ311,
		@bQ312,
		@bQ313,
		@bQ41,
		@bQ42,
		@bQ43,
		@bQ44,
		@bQ45,
		@bQ46,
		@dQ5Ith,
		@bQ61,
		@bQ62,
		@bQ63,
		@bQ64,
		@bQ65,
		@bQ66,
		@bIsValid,
		@sInvalidRemark,
		@sCreateDate
	)
    
	SET @iSecondStagingPscRmwCipID = ISNULL(@@IDENTITY, 0)
	SELECT @iSecondStagingPscRmwCipID
END
