CREATE TABLE [dbo].[COM_EDUCATION] (
    [COM_EDUCATION_ID] INT           CONSTRAINT [DF_COM_EDUCATION_COM_EDUCATION_ID] DEFAULT ((0)) NOT NULL,
    [EDUCATION_NAME]   VARCHAR (100) CONSTRAINT [DF_COM_EDUCATION_EDUCATION_NAME] DEFAULT ('-') NOT NULL,
    [DESCRIPTION]      VARCHAR (255) CONSTRAINT [DF_COM_EDUCATION_DESCRIPTION] DEFAULT ('-') NOT NULL,
    CONSTRAINT [PK_COM_EDUCATION] PRIMARY KEY CLUSTERED ([COM_EDUCATION_ID] ASC)
);

