CREATE TABLE [dbo].[COM_CURRENCY] (
    [COM_CURRENCY_ID]   INT           NOT NULL,
    [CURRENCY_CODE]     VARCHAR (3)   CONSTRAINT [DF_COM_CURRENCY_CURRENCY_CODE] DEFAULT ('-') NOT NULL,
    [DESCRIPTION]       VARCHAR (100) CONSTRAINT [DF_COM_CURRENCY_DESCRIPTION] DEFAULT ('-') NOT NULL,
    [IS_ACTIVE]         BIT           CONSTRAINT [DF_COM_CURRENCY_IS_ACTIVE] DEFAULT ((0)) NOT NULL,
    [IS_DELETED]        BIT           CONSTRAINT [DF_COM_CURRENCY_IS_DELETED] DEFAULT ((0)) NOT NULL,
    [CREATE_DATE]       DATETIME      CONSTRAINT [DF_COM_CURRENCY_CREATE_DATE] DEFAULT (((1900)-(1))-(1)) NOT NULL,
    [CREATE_BY_USER_ID] INT           CONSTRAINT [DF_COM_CURRENCY_CREATE_BY_USER_ID] DEFAULT ((0)) NOT NULL,
    [UPDATE_DATE]       DATETIME      CONSTRAINT [DF_COM_CURRENCY_UPDATE_DATE] DEFAULT (((1900)-(1))-(1)) NOT NULL,
    [UPDATE_BY_USER_ID] INT           NOT NULL,
    CONSTRAINT [PK_COM_CURRENCY] PRIMARY KEY CLUSTERED ([COM_CURRENCY_ID] ASC)
);

