CREATE TABLE [dbo].[COM_APPROVAL_STATUS] (
    [COM_APPROVAL_STATUS_ID]   SMALLINT      CONSTRAINT [DF_COM_APPROVAL_STATUS_COM_APPROVAL_STATUS_ID] DEFAULT ((0)) NOT NULL,
    [COM_APPROVAL_STATUS_CODE] VARCHAR (50)  CONSTRAINT [DF_COM_APPROVAL_STATUS_COM_APPROVAL_STATUS_CODE] DEFAULT ('NONE') NOT NULL,
    [DESCRIPTION]              VARCHAR (255) CONSTRAINT [DF_COM_APPROVAL_STATUS_DESCRIPTION] DEFAULT ('NONE') NOT NULL,
    CONSTRAINT [PK_COM_APPROVAL_STATUS] PRIMARY KEY CLUSTERED ([COM_APPROVAL_STATUS_ID] ASC)
);

