CREATE TABLE [dbo].[COM_PRODUCT_RATING] (
    [COM_PRODUCT_RATING_ID] INT           IDENTITY (1, 1) NOT NULL,
    [RATING_SCORE]          VARCHAR (5)   CONSTRAINT [DF_COM_PRODUCT_RATING_RATING_SCORE] DEFAULT ('-') NOT NULL,
    [DESCRIPTION]           VARCHAR (255) CONSTRAINT [DF_COM_PRODUCT_RATING_DESCRIPTION] DEFAULT ('-') NOT NULL,
    CONSTRAINT [PK_COM_PRODUCT_RATING] PRIMARY KEY CLUSTERED ([COM_PRODUCT_RATING_ID] ASC)
);

