CREATE TABLE [dbo].[COM_RM] (
    [COM_RM_ID]         INT           IDENTITY (1, 1) NOT NULL,
    [RM_CODE]           VARCHAR (10)  CONSTRAINT [DF_COM_RM_RM_CODE] DEFAULT ('-') NOT NULL,
    [RM_NAME]           VARCHAR (255) CONSTRAINT [DF_COM_RM_RM_NAME] DEFAULT ('-') NOT NULL,
    [IS_DELETED]        BIT           CONSTRAINT [DF_COM_RM_IS_DELETED] DEFAULT ((0)) NOT NULL,
    [CREATE_DATE]       DATETIME      CONSTRAINT [DF_COM_RM_CREATE_DATE] DEFAULT ('1900-01-01') NOT NULL,
    [CREATE_BY_USER_ID] INT           CONSTRAINT [DF_COM_RM_CREATE_BY_USER_ID] DEFAULT ((0)) NOT NULL,
    [UPDATE_DATE]       DATETIME      CONSTRAINT [DF_COM_RM_UPDATE_DATE] DEFAULT ('1900-01-01') NOT NULL,
    [UPDATE_BY_USER_ID] INT           CONSTRAINT [DF_COM_RM_UPDATE_BY_USER_ID] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_COM_RM] PRIMARY KEY CLUSTERED ([COM_RM_ID] ASC)
);

