CREATE TABLE [dbo].[COM_APPROVAL_LOG] (
    [COM_APPROVAL_LOG_ID]         BIGINT        IDENTITY (1, 1) NOT NULL,
    [REF_ID]                      INT           CONSTRAINT [DF_COM_APPROVAL_LOG_REF_ID] DEFAULT ((0)) NOT NULL,
    [PFS_MODULE_OBJECT_MEMBER_ID] INT           CONSTRAINT [DF_COM_APPROVAL_LOG_PFS_MODULE_OBJECT_MEMBER_ID] DEFAULT ((0)) NOT NULL,
    [COM_APPROVAL_STATUS_ID]      SMALLINT      CONSTRAINT [DF_COM_APPROVAL_LOG_COM_APPROVAL_STATUS_ID] DEFAULT ((0)) NOT NULL,
    [CREATE_DATE]                 DATETIME      CONSTRAINT [DF_COM_APPROVAL_LOG_CREATE_DATE] DEFAULT ('1/1/1900') NOT NULL,
    [UPDATE_DATE]                 DATETIME      CONSTRAINT [DF_COM_APPROVAL_LOG_UPDATE_DATE] DEFAULT ('1/1/1900') NOT NULL,
    [CREATE_BY_USER_ID]           INT           CONSTRAINT [DF_COM_APPROVAL_LOG_CREATE_BY_USER_ID] DEFAULT ((0)) NOT NULL,
    [UPDATE_BY_USER_ID]           INT           CONSTRAINT [DF_COM_APPROVAL_LOG_UPDATE_BY_USER_ID] DEFAULT ((0)) NOT NULL,
    [DETAIL]                      XML           NOT NULL,
    [REMARK]                      VARCHAR (255) CONSTRAINT [DF_COM_APPROVAL_LOG_REMARK] DEFAULT ('NONE') NOT NULL,
    [PREVIOUS_DETAIL]             XML           CONSTRAINT [DF_COM_APPROVAL_LOG_PREVIOUS_DETAIL] DEFAULT ('<xml />') NOT NULL,
    CONSTRAINT [PK_COM_APPROVAL_LOG] PRIMARY KEY CLUSTERED ([COM_APPROVAL_LOG_ID] ASC),
    CONSTRAINT [COM_APPROVAL_LOG_fk] FOREIGN KEY ([PFS_MODULE_OBJECT_MEMBER_ID]) REFERENCES [dbo].[PFS_MODULE_OBJECT_MEMBER] ([PFS_MODULE_OBJECT_MEMBER_ID]),
    CONSTRAINT [COM_APPROVAL_LOG_fk2] FOREIGN KEY ([COM_APPROVAL_STATUS_ID]) REFERENCES [dbo].[COM_APPROVAL_STATUS] ([COM_APPROVAL_STATUS_ID])
);

