CREATE TABLE [dbo].[COM_CUSTOMER] (
    [COM_CUSTOMER_ID]    INT           IDENTITY (1, 1) NOT NULL,
    [PSC_FILE_IMPORT_ID] INT           NOT NULL,
    [CIF]                VARCHAR (15)  NOT NULL,
    [CUSTOMER_DOB]       DATETIME      CONSTRAINT [DF_COM_CUSTOMER_CUSTOMER_DOB] DEFAULT (((1900)-(1))-(1)) NOT NULL,
    [CONTROL_CENTER]     VARCHAR (5)   NOT NULL,
    [COM_EDUCATION_ID]   INT           CONSTRAINT [DF_COM_CUSTOMER_COM_EDUCATION_ID] DEFAULT ((0)) NOT NULL,
    [FULL_NAME]          VARCHAR (255) NOT NULL,
    [COM_BRANCH_ID]      INT           NOT NULL,
    [FIELD_RESERVE_1]    VARCHAR (100) CONSTRAINT [DF_COM_CUSTOMER_FIELD_RESERVE_1] DEFAULT ('-') NOT NULL,
    [FIELD_RESERVE_2]    VARCHAR (100) CONSTRAINT [DF_COM_CUSTOMER_FIELD_RESERVE_2] DEFAULT ('-') NOT NULL,
    [FIELD_RESERVE_3]    VARCHAR (100) CONSTRAINT [DF_COM_CUSTOMER_FIELD_RESERVE_3] DEFAULT ('-') NOT NULL,
    [IS_ACTIVE]          BIT           CONSTRAINT [DF_COM_CUSTOMER_IS_ACTIVE] DEFAULT ((1)) NOT NULL,
    [IS_DELETED]         BIT           CONSTRAINT [DF_COM_CUSTOMER_IS_DELETED] DEFAULT ((0)) NOT NULL,
    [CREATE_DATE]        DATETIME      CONSTRAINT [DF_COM_CUSTOMER_CREATE_DATE] DEFAULT ('1900-01-01') NOT NULL,
    [CREATE_BY_USER_ID]  INT           CONSTRAINT [DF_COM_CUSTOMER_CREATE_BY_USER_ID] DEFAULT ((0)) NOT NULL,
    [UPDATE_DATE]        DATETIME      CONSTRAINT [DF_COM_CUSTOMER_UPDATE_DATE] DEFAULT ('1900-01-01') NOT NULL,
    [UPDATE_BY_USER_ID]  INT           CONSTRAINT [DF_COM_CUSTOMER_UPDATE_BY_USER_ID] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_COM_CUSTOMER] PRIMARY KEY CLUSTERED ([COM_CUSTOMER_ID] ASC),
    CONSTRAINT [FK_COM_CUSTOMER_COM_BRANCH] FOREIGN KEY ([COM_BRANCH_ID]) REFERENCES [dbo].[COM_BRANCH] ([COM_BRANCH_ID]),
    CONSTRAINT [FK_COM_CUSTOMER_PSC_FILE_IMPORT] FOREIGN KEY ([PSC_FILE_IMPORT_ID]) REFERENCES [dbo].[PSC_FILE_IMPORT] ([PSC_FILE_IMPORT_ID])
);

