CREATE TABLE [dbo].[COM_BRANCH] (
    [COM_BRANCH_ID]     INT           IDENTITY (1, 1) NOT NULL,
    [BRANCH_CODE]       VARCHAR (20)  CONSTRAINT [DF_COM_BRANCH_BRANCH_CODE] DEFAULT ('-') NOT NULL,
    [BRANCH_NAME]       VARCHAR (100) CONSTRAINT [DF_COM_BRANCH_BRANCH_NAME] DEFAULT ('-') NOT NULL,
    [DESCRIPTION]       VARCHAR (255) CONSTRAINT [DF_COM_BRANCH_DESCRIPTION] DEFAULT ('-') NOT NULL,
    [IS_ACTIVE]         BIT           CONSTRAINT [DF_COM_BRANCH_IS_ACTIVE] DEFAULT ((1)) NOT NULL,
    [IS_DELETED]        BIT           CONSTRAINT [DF_COM_BRANCH_IS_DELETED] DEFAULT ((0)) NOT NULL,
    [CREATE_DATE]       DATETIME      CONSTRAINT [DF_COM_BRANCH_CREATE_DATE] DEFAULT (((1900)-(1))-(1)) NOT NULL,
    [CREATE_BY_USER_ID] INT           CONSTRAINT [DF_COM_BRANCH_CREATE_BY_USER_ID] DEFAULT ((0)) NOT NULL,
    [UPDATE_DATE]       DATETIME      CONSTRAINT [DF_COM_BRANCH_UPDATE_DATE] DEFAULT (((1900)-(1))-(1)) NOT NULL,
    [UPDATE_BY_USER_ID] INT           CONSTRAINT [DF_COM_BRANCH_UPDATE_BY_USER_ID] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_COM_BRANCH] PRIMARY KEY CLUSTERED ([COM_BRANCH_ID] ASC)
);

