CREATE TABLE [dbo].[COM_OPERATOR] (
    [COM_OPERATOR_ID]   INT          NOT NULL,
    [OPERATOR_CODE]     VARCHAR (3)  CONSTRAINT [DF_COM_OPERATOR_OPERATOR_CODE] DEFAULT ('-') NOT NULL,
    [OPERATOR_NAME]     VARCHAR (10) CONSTRAINT [DF_COM_OPERATOR_OPERATOR_NAME] DEFAULT ('-') NOT NULL,
    [IS_ACTIVE]         BIT          CONSTRAINT [DF_COM_OPERATOR_IS_ACTIVE] DEFAULT ((0)) NOT NULL,
    [CREATE_DATE]       DATETIME     CONSTRAINT [DF_COM_OPERATOR_CREATE_DATE] DEFAULT (((1900)-(1))-(1)) NOT NULL,
    [CREATE_BY_USER_ID] INT          CONSTRAINT [DF_COM_OPERATOR_CREATE_BY_USER_ID] DEFAULT ((0)) NOT NULL,
    [UPDATE_DATE]       DATETIME     CONSTRAINT [DF_COM_OPERATOR_UPDATE_DATE] DEFAULT (((1900)-(1))-(1)) NOT NULL,
    [UPDATE_BY_USER_ID] INT          CONSTRAINT [DF_COM_OPERATOR_UPDATE_BY_USER_ID] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_COM_OPERATOR] PRIMARY KEY CLUSTERED ([COM_OPERATOR_ID] ASC)
);

