CREATE TABLE [dbo].[PFS_AUTONUMBER_PATTERN] (
    [PFS_AUTONUMBER_PATTERN_ID] INT          IDENTITY (1, 1) NOT NULL,
    [PFS_AUTONUMBER_OBJECT_ID]  INT          NOT NULL,
    [REFERENCE_ID]              INT          NOT NULL,
    [FORMAT_PATTERN]            VARCHAR (50) NOT NULL,
    [FORMAT_YEAR]               VARCHAR (4)  NOT NULL,
    [FORMAT_MONTH]              VARCHAR (4)  NOT NULL,
    [FORMAT_DAY]                VARCHAR (2)  NOT NULL,
    [FORMAT_COUNTER]            TINYINT      NOT NULL,
    [FORMAT_CHARACTER]          TINYINT      NOT NULL,
    [RESET_TYPE]                VARCHAR (4)  NOT NULL,
    CONSTRAINT [PK_PFS_AUTONUMBER_PATTERN] PRIMARY KEY CLUSTERED ([PFS_AUTONUMBER_PATTERN_ID] ASC),
    CONSTRAINT [PFS_AUTONUMBER_OBJECT_PFS_AUTONUMBER_PATTERN_FK1] FOREIGN KEY ([PFS_AUTONUMBER_OBJECT_ID]) REFERENCES [dbo].[PFS_AUTONUMBER_OBJECT] ([PFS_AUTONUMBER_OBJECT_ID])
);

