CREATE TABLE [dbo].[PFS_USER_LOG] (
    [PFS_USER_LOG_ID]             BIGINT         IDENTITY (1, 1) NOT NULL,
    [PFS_USER_ID]                 INT            CONSTRAINT [DF__PFS_USER___PFS_U__509BDCCF] DEFAULT ((0)) NULL,
    [USER_NAME]                   VARCHAR (50)   CONSTRAINT [DF_PFS_USER_LOG_USER_NAME] DEFAULT ('-') NOT NULL,
    [REFERENCE_NUMBER]            VARCHAR (25)   CONSTRAINT [DF__PFS_USER___REFER__51900108] DEFAULT ('-') NULL,
    [IP_ADDRESS]                  VARCHAR (50)   CONSTRAINT [DF__PFS_USER___IP_AD__52842541] DEFAULT ('-') NOT NULL,
    [LOG_DATE]                    DATETIME       CONSTRAINT [DF__PFS_USER___LOG_D__5378497A] DEFAULT ('1900-01-01') NOT NULL,
    [DESCRIPTION]                 VARCHAR (1280) CONSTRAINT [DF__PFS_USER___DESCR__546C6DB3] DEFAULT ('-') NULL,
    [DETAIL]                      XML            CONSTRAINT [DF__PFS_USER___DETAI__556091EC] DEFAULT ('<xml />') NULL,
    [STATUS]                      SMALLINT       CONSTRAINT [DF__PFS_USER___STATU__5654B625] DEFAULT ((0)) NOT NULL,
    [PFS_MODULE_OBJECT_MEMBER_ID] INT            CONSTRAINT [DF__PFS_USER___PFS_M__5748DA5E] DEFAULT ((0)) NOT NULL,
    [IS_PURGE]                    BIT            CONSTRAINT [DF_PFS_USER_LOG_IS_PURGE] DEFAULT ((0)) NOT NULL,
    [PREVIOUS_DETAIL]             XML            CONSTRAINT [DF_PFS_USER_LOG_PREVIOUS_DETAIL] DEFAULT ('<xml />') NOT NULL,
    CONSTRAINT [PK__PFS_USER__465007FE4EB3945D] PRIMARY KEY CLUSTERED ([PFS_USER_LOG_ID] ASC) ON [ANZ_PSC_ErrorLog]
) TEXTIMAGE_ON [ANZ_PSC_ErrorLog];

