CREATE TABLE [dbo].[PFS_MODULE_OBJECT_MEMBER_USER_ACTION] (
    [PFS_MODULE_OBJECT_MEMBER_USER_ACTION_ID] INT IDENTITY (1, 1) NOT NULL,
    [PFS_MODULE_OBJECT_MEMBER_ID]             INT NOT NULL,
    [PFS_MODULE_OBJECT_ID]                    INT NOT NULL,
    [USER_ACTION_TYPE]                        INT NOT NULL,
    CONSTRAINT [PK_PFS_MODULE_OBJECT_MEMBER_USER_ACTION] PRIMARY KEY CLUSTERED ([PFS_MODULE_OBJECT_MEMBER_USER_ACTION_ID] ASC),
    CONSTRAINT [FK_PFS_MODULE_OBJECT_MEMBER_USER_ACTION_PFS_MODULE_OBJECT] FOREIGN KEY ([PFS_MODULE_OBJECT_ID]) REFERENCES [dbo].[PFS_MODULE_OBJECT] ([PFS_MODULE_OBJECT_ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_PFS_MODULE_OBJECT_MEMBER_USER_ACTION_PFS_MODULE_OBJECT_MEMBER] FOREIGN KEY ([PFS_MODULE_OBJECT_MEMBER_ID]) REFERENCES [dbo].[PFS_MODULE_OBJECT_MEMBER] ([PFS_MODULE_OBJECT_MEMBER_ID]) ON DELETE CASCADE
);

