CREATE TABLE [dbo].[PFS_USER_GROUP] (
    [PFS_USER_GROUP_ID] INT IDENTITY (1, 1) NOT NULL,
    [PFS_USER_ID]       INT NOT NULL,
    [PFS_GROUP_ID]      INT NOT NULL,
    CONSTRAINT [PK_PFS_USER_GROUP] PRIMARY KEY CLUSTERED ([PFS_USER_GROUP_ID] ASC),
    CONSTRAINT [FK_PFS_USER_GROUP_PFS_GROUP] FOREIGN KEY ([PFS_GROUP_ID]) REFERENCES [dbo].[PFS_GROUP] ([PFS_GROUP_ID]),
    CONSTRAINT [FK_PFS_USER_GROUP_PFS_USER] FOREIGN KEY ([PFS_USER_ID]) REFERENCES [dbo].[PFS_USER] ([PFS_USER_ID])
);

