CREATE TABLE [dbo].[PFS_USER_PASSWORD_HISTORY] (
    [PFS_USER_PASSWORD_HISTORY_ID] BIGINT        IDENTITY (1, 1) NOT NULL,
    [PFS_USER_ID]                  INT           CONSTRAINT [DF_PFS_USER_PASSWORD_HISTORY_PFS_USER_ID] DEFAULT ((0)) NOT NULL,
    [PASSWORD]                     VARCHAR (255) CONSTRAINT [DF_PFS_USER_PASSWORD_HISTORY_PASSWORD] DEFAULT ('NONE') NOT NULL,
    [CREATE_DATE]                  DATETIME      CONSTRAINT [DF_PFS_USER_PASSWORD_HISTORY_CREATE_DATE] DEFAULT ('1900-01-01') NOT NULL,
    CONSTRAINT [PK_PFS_USER_PASSWORD_HISTORY] PRIMARY KEY CLUSTERED ([PFS_USER_PASSWORD_HISTORY_ID] ASC),
    CONSTRAINT [FK_PFS_USER_PASSWORD_HISTORY_PFS_USER1] FOREIGN KEY ([PFS_USER_ID]) REFERENCES [dbo].[PFS_USER] ([PFS_USER_ID]) ON DELETE CASCADE
);

