CREATE TABLE [dbo].[PFS_AUTONUMBER_OBJECT] (
    [PFS_AUTONUMBER_OBJECT_ID] INT           IDENTITY (1, 1) NOT NULL,
    [OBJECT_CODE]              VARCHAR (50)  NOT NULL,
    [OBJECT_NAME]              VARCHAR (100) NOT NULL,
    [OBJECT_DESCR]             VARCHAR (500) NOT NULL,
    CONSTRAINT [PK_PFS_AUTONUMBER_OBJECT] PRIMARY KEY CLUSTERED ([PFS_AUTONUMBER_OBJECT_ID] ASC)
);

