CREATE TABLE [dbo].[PFS_HOLIDAY_DATE] (
    [PFS_HOLIDAY_DATE_ID] INT      IDENTITY (1, 1) NOT NULL,
    [PFS_HOLIDAY_ID]      INT      NOT NULL,
    [HOLIDAY_DATE]        DATETIME NOT NULL,
    CONSTRAINT [PK_PFS_HOLIDAY_DATE] PRIMARY KEY CLUSTERED ([PFS_HOLIDAY_DATE_ID] ASC),
    CONSTRAINT [PFS_HOLIDAY_PFS_HOLIDAY_DATE_FK1] FOREIGN KEY ([PFS_HOLIDAY_ID]) REFERENCES [dbo].[PFS_HOLIDAY] ([PFS_HOLIDAY_ID])
);

