CREATE TABLE [dbo].[PFS_MODULE_OBJECT_MEMBER] (
    [PFS_MODULE_OBJECT_MEMBER_ID] INT           NOT NULL,
    [PFS_MODULE_OBJECT_ID]        INT           CONSTRAINT [DF_PFS_MODULE_OBJECT_MEMBER_PFS_MODULE_OBJECT_ID] DEFAULT ((0)) NOT NULL,
    [MEMBER_CODE]                 VARCHAR (50)  CONSTRAINT [DF_PFS_MODULE_OBJECT_MEMBER_MEMBER_CODE] DEFAULT ('NONE') NOT NULL,
    [MEMBER_NAME]                 VARCHAR (100) CONSTRAINT [DF_PFS_MODULE_OBJECT_MEMBER_MEMBER_NAME] DEFAULT ('NONE') NOT NULL,
    [MEMBER_DESCR]                VARCHAR (500) CONSTRAINT [DF_PFS_MODULE_OBJECT_MEMBER_MEMBER_DESCR] DEFAULT ('NONE') NOT NULL,
    [INDEX_ORDER]                 SMALLINT      NOT NULL,
    [IS_WITH_APPROVAL_PROCCESS]   BIT           CONSTRAINT [DF_PFS_MODULE_OBJECT_MEMBER_IS_WITH_APPROVAL_PROCCESS] DEFAULT ((0)) NOT NULL,
    [IS_VISIBLE]                  BIT           CONSTRAINT [DF__PFS_MODUL__IS_VI__68143F04] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_COM_MODULE_OBJECT_MEMBER] PRIMARY KEY CLUSTERED ([PFS_MODULE_OBJECT_MEMBER_ID] ASC),
    CONSTRAINT [FK_COM_MODULE_OBJECT_MEMBER_COM_MODULE_OBJECT] FOREIGN KEY ([PFS_MODULE_OBJECT_ID]) REFERENCES [dbo].[PFS_MODULE_OBJECT] ([PFS_MODULE_OBJECT_ID]),
    CONSTRAINT [FK_PFS_MODULE_OBJECT_MEMBER_PFS_MODULE_OBJECT] FOREIGN KEY ([PFS_MODULE_OBJECT_ID]) REFERENCES [dbo].[PFS_MODULE_OBJECT] ([PFS_MODULE_OBJECT_ID])
);

