CREATE TABLE [dbo].[PFS_EMAIL_NOTIFICATION] (
    [PFS_EMAIL_NOTIFICATION_ID] INT           NOT NULL,
    [TYPE]                      VARCHAR (50)  NOT NULL,
    [KEYWORD]                   VARCHAR (255) NOT NULL,
    [PRIORITY]                  INT           NOT NULL,
    CONSTRAINT [PK_PFS_EMAIL_TYPE] PRIMARY KEY CLUSTERED ([PFS_EMAIL_NOTIFICATION_ID] ASC)
);

