CREATE TABLE [dbo].[PFS_EXCEPTION_LOG] (
    [PFS_EXCEPTION_LOG_ID] BIGINT         IDENTITY (1, 1) NOT NULL,
    [REFERENCE_NUMBER]     VARCHAR (25)   DEFAULT ('-') NOT NULL,
    [LOG_DATE]             DATETIME       DEFAULT ('1900-01-01') NOT NULL,
    [SOURCE]               VARCHAR (255)  DEFAULT ('-') NOT NULL,
    [DESCRIPTION]          VARCHAR (8000) DEFAULT ('-') NOT NULL,
    PRIMARY KEY CLUSTERED ([PFS_EXCEPTION_LOG_ID] ASC) ON [ANZ_PSC_ErrorLog]
);

