CREATE TABLE [dbo].[PFS_USER_DETAIL] (
    [PFS_USER_DETAIL_ID] INT           IDENTITY (1, 1) NOT NULL,
    [PFS_USER_ID]        INT           NOT NULL,
    [USER_CODE]          VARCHAR (20)  NOT NULL,
    [BRANCH_CODE]        VARCHAR (100) NULL,
    [DEPARTMENT_NAME]    VARCHAR (100) NULL,
    [POSITION]           VARCHAR (100) NULL,
    [DOB]                DATETIME      NULL,
    [HOME_NUMBER]        VARCHAR (50)  NULL,
    [WORK_NUMBER]        VARCHAR (50)  NULL,
    [MOBILE_NUMBER]      VARCHAR (30)  NULL,
    [PICTURE]            IMAGE         NULL,
    CONSTRAINT [PK_PFS_USER_DETAIL] PRIMARY KEY CLUSTERED ([PFS_USER_DETAIL_ID] ASC),
    CONSTRAINT [FK_PFS_USER_DETAIL_PFS_USER] FOREIGN KEY ([PFS_USER_ID]) REFERENCES [dbo].[PFS_USER] ([PFS_USER_ID])
);

