CREATE TABLE [dbo].[PFS_MODULE_OBJECT] (
    [PFS_MODULE_OBJECT_ID] INT           NOT NULL,
    [PFS_MODULE_ID]        INT           CONSTRAINT [DF_PFS_MODULE_OBJECT_PFS_MODULE_ID] DEFAULT ((0)) NOT NULL,
    [OBJECT_CODE]          VARCHAR (50)  CONSTRAINT [DF_PFS_MODULE_OBJECT_OBJECT_CODE] DEFAULT ('NONE') NOT NULL,
    [OBJECT_NAME]          VARCHAR (100) CONSTRAINT [DF_PFS_MODULE_OBJECT_OBJECT_NAME] DEFAULT ('NONE') NOT NULL,
    [OBJECT_DESCR]         VARCHAR (500) CONSTRAINT [DF_PFS_MODULE_OBJECT_OBJECT_DESCR] DEFAULT ('NONE') NOT NULL,
    [INDEX_ORDER]          SMALLINT      NOT NULL,
    [IS_VISIBLE]           BIT           CONSTRAINT [DF__PFS_MODUL__IS_VI__67201ACB] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_COM_MODULE_OBJECT] PRIMARY KEY CLUSTERED ([PFS_MODULE_OBJECT_ID] ASC),
    CONSTRAINT [FK_COM_MODULE_OBJECT_COM_MODULE] FOREIGN KEY ([PFS_MODULE_ID]) REFERENCES [dbo].[PFS_MODULE] ([PFS_MODULE_ID]),
    CONSTRAINT [FK_PFS_MODULE_OBJECT_PFS_MODULE] FOREIGN KEY ([PFS_MODULE_ID]) REFERENCES [dbo].[PFS_MODULE] ([PFS_MODULE_ID]) ON DELETE CASCADE
);

