CREATE TABLE [dbo].[PFS_MODULE_OBJECT_MEMBER_GROUP] (
    [PFS_MODULE_OBJECT_MEMBER_GROUP_ID] INT IDENTITY (1, 1) NOT NULL,
    [PFS_MODULE_ID]                     INT NOT NULL,
    [PFS_MODULE_OBJECT_ID]              INT NOT NULL,
    [PFS_MODULE_OBJECT_MEMBER_ID]       INT NOT NULL,
    [PFS_GROUP_ID]                      INT NOT NULL,
    CONSTRAINT [PK_COM_MODULE_OBJECT_MEMBER_GROUP] PRIMARY KEY CLUSTERED ([PFS_MODULE_OBJECT_MEMBER_GROUP_ID] ASC),
    CONSTRAINT [FK_COM_MODULE_OBJECT_MEMBER_GROUP_COM_GROUP] FOREIGN KEY ([PFS_GROUP_ID]) REFERENCES [dbo].[PFS_GROUP] ([PFS_GROUP_ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_COM_MODULE_OBJECT_MEMBER_GROUP_COM_MODULE_OBJECT_MEMBER] FOREIGN KEY ([PFS_MODULE_OBJECT_MEMBER_ID]) REFERENCES [dbo].[PFS_MODULE_OBJECT_MEMBER] ([PFS_MODULE_OBJECT_MEMBER_ID]),
    CONSTRAINT [PFS_MODULE_OBJECT_PFS_MODULE_OBJECT_MEMBER_GROUP_FK1] FOREIGN KEY ([PFS_MODULE_OBJECT_ID]) REFERENCES [dbo].[PFS_MODULE_OBJECT] ([PFS_MODULE_OBJECT_ID]),
    CONSTRAINT [PFS_MODULE_PFS_MODULE_OBJECT_MEMBER_GROUP_FK1] FOREIGN KEY ([PFS_MODULE_ID]) REFERENCES [dbo].[PFS_MODULE] ([PFS_MODULE_ID])
);

