CREATE TABLE [dbo].[PFS_AUTONUMBER_COUNTER] (
    [PFS_AUTONUMBER_COUNTER_ID] INT         IDENTITY (1, 1) NOT NULL,
    [PFS_AUTONUMBER_PATTERN_ID] INT         NOT NULL,
    [PERIOD_YEAR]               SMALLINT    NOT NULL,
    [PERIOD_MONTH]              TINYINT     NOT NULL,
    [PERIOD_DAY]                TINYINT     NOT NULL,
    [LATEST_COUNTER]            INT         NOT NULL,
    [LATEST_CHARACTER]          VARCHAR (5) NOT NULL,
    CONSTRAINT [PK_PFS_AUTONUMBER_COUNTER] PRIMARY KEY CLUSTERED ([PFS_AUTONUMBER_COUNTER_ID] ASC),
    CONSTRAINT [PFS_AUTONUMBER_PATTERN_PFS_AUTONUMBER_COUNTER_FK1] FOREIGN KEY ([PFS_AUTONUMBER_PATTERN_ID]) REFERENCES [dbo].[PFS_AUTONUMBER_PATTERN] ([PFS_AUTONUMBER_PATTERN_ID])
);

