CREATE TABLE [dbo].[PFS_SYS_PARAM_GROUP] (
    [PFS_SYS_PARAM_GROUP_ID] INT           NOT NULL,
    [PARAM_GROUP_NAME]       VARCHAR (100) NOT NULL,
    [GROUP_DESCR]            VARCHAR (500) NOT NULL,
    [INDEX_ORDER]            INT           NOT NULL,
    [IS_VISIBLE]             BIT           NOT NULL,
    CONSTRAINT [PK_PFS_SYS_PARAM_GROUP] PRIMARY KEY CLUSTERED ([PFS_SYS_PARAM_GROUP_ID] ASC)
);

