CREATE TABLE [dbo].[PSC_EXCEPTION_FORM] (
    [PSC_EXCEPTION_FORM_ID] INT           IDENTITY (1, 1) NOT NULL,
    [COM_BRANCH_ID]         INT           CONSTRAINT [DF_PSC_EXCEPTION_FORM_COM_BRANCH_ID] DEFAULT ((0)) NOT NULL,
    [BRANCH_NAME]           VARCHAR (100) NOT NULL,
    [CIF]                   VARCHAR (15)  NOT NULL,
    [CUSTOMER_FULL_NAME]    VARCHAR (255) NOT NULL,
    [COM_ASSET_CLASS_ID]    INT           NOT NULL,
    [COM_PRODUCT_RATING_ID] INT           NOT NULL,
    [EXCEPTION_DATE]        DATETIME      NOT NULL,
    [APPROVED_DATE]         DATETIME      NOT NULL,
    [EXPIRY_DATE]           DATETIME      NOT NULL,
    [IS_ACTIVE]             BIT           NOT NULL,
    [IS_DELETED]            BIT           NOT NULL,
    [CREATE_DATE]           DATETIME      NOT NULL,
    [CREATE_BY_USER_ID]     INT           NOT NULL,
    [UPDATE_DATE]           DATETIME      NOT NULL,
    [UPDATE_BY_USER_ID]     INT           NOT NULL,
    [IS_NEED_APPROVAL]      BIT           CONSTRAINT [DF_PSC_EXCEPTION_FORM_IS_NEED_APPROVAL] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_PSC_EXCEPTION_FORM] PRIMARY KEY CLUSTERED ([PSC_EXCEPTION_FORM_ID] ASC),
    CONSTRAINT [FK_PSC_EXCEPTION_FORM_COM_ASSET_CLASS] FOREIGN KEY ([COM_ASSET_CLASS_ID]) REFERENCES [dbo].[COM_ASSET_CLASS] ([COM_ASSET_CLASS_ID]),
    CONSTRAINT [FK_PSC_EXCEPTION_FORM_COM_PRODUCT_RATING] FOREIGN KEY ([COM_PRODUCT_RATING_ID]) REFERENCES [dbo].[COM_PRODUCT_RATING] ([COM_PRODUCT_RATING_ID])
);

