CREATE TABLE [dbo].[PSC_CUSTOMER_RATING_VS_PRODUCT_RATING] (
    [PSC_CUSTOMER_RATING_VS_PRODUCT_RATING_ID] INT          DEFAULT ((0)) NOT NULL,
    [COM_CUSTOMER_RISK_RATING_ID]              INT          DEFAULT ((0)) NOT NULL,
    [PRODUCT_RATING_TO_WITH_EXCEPTION]         VARCHAR (25) DEFAULT ('-') NOT NULL,
    [PRODUCT_RATING_TO_WITH_NO_EXCEPTION]      VARCHAR (25) DEFAULT ('-') NOT NULL,
    [IS_ACTIVE]                                BIT          DEFAULT ((0)) NOT NULL,
    [CREATE_DATE]                              DATETIME     DEFAULT ('1900-01-01') NOT NULL,
    [CREATE_BY_USER_ID]                        INT          DEFAULT ((0)) NOT NULL,
    [UPDATE_DATE]                              DATETIME     DEFAULT ('1900-01-01') NOT NULL,
    [UPDATE_BY_USER_ID]                        INT          DEFAULT ((0)) NOT NULL,
    PRIMARY KEY CLUSTERED ([PSC_CUSTOMER_RATING_VS_PRODUCT_RATING_ID] ASC),
    FOREIGN KEY ([COM_CUSTOMER_RISK_RATING_ID]) REFERENCES [dbo].[COM_CUSTOMER_RISK_RATING] ([COM_CUSTOMER_RISK_RATING_ID])
);

