CREATE TABLE [dbo].[PSC_PROFILE_MISMATCH_MATRIX] (
    [PSC_PROFILE_MISMATCH_MATRIX_ID] INT        IDENTITY (1, 1) NOT NULL,
    [COM_ASSET_CLASS_ID]             INT        CONSTRAINT [DF_PSC_PROFILE_MISMATCH_MATRIX_COM_ASSET_CLASS_ID] DEFAULT ((0)) NOT NULL,
    [COM_PRODUCT_RATING_ID]          INT        CONSTRAINT [DF_PSC_PROFILE_MISMATCH_MATRIX_COM_PRODUCT_RATING_ID] DEFAULT ((0)) NOT NULL,
    [OPERATOR_ID_YES]                INT        CONSTRAINT [DF_PSC_PROFILE_MISMATCH_MATRIX_OPERATOR_ID_YES] DEFAULT ((0)) NOT NULL,
    [VALUE_NO_PERCENT]               FLOAT (53) CONSTRAINT [DF_PSC_PROFILE_MISMATCH_MATRIX_VALUE_NO_PERCENT] DEFAULT ((0)) NOT NULL,
    [OPERATOR_ID_NO]                 INT        CONSTRAINT [DF_PSC_PROFILE_MISMATCH_MATRIX_OPERATOR_ID_NO] DEFAULT ((0)) NOT NULL,
    [VALUE_YES_PERCENT]              FLOAT (53) CONSTRAINT [DF_PSC_PROFILE_MISMATCH_MATRIX_VALUE_YES_PERCENT] DEFAULT ((0)) NOT NULL,
    [IS_ACTIVE]                      BIT        CONSTRAINT [DF_PSC_PROFILE_MISMATCH_MATRIX_IS_ACTIVE] DEFAULT ((0)) NOT NULL,
    [CREATE_DATE]                    DATETIME   CONSTRAINT [DF_PSC_PROFILE_MISMATCH_MATRIX_CREATE_DATE] DEFAULT (((1900)-(1))-(1)) NOT NULL,
    [CREATE_BY_USER_ID]              INT        CONSTRAINT [DF_PSC_PROFILE_MISMATCH_MATRIX_CREATE_BY_USER_ID] DEFAULT ((0)) NOT NULL,
    [UPDATE_DATE]                    DATETIME   CONSTRAINT [DF_PSC_PROFILE_MISMATCH_MATRIX_UPDATE_DATE] DEFAULT (((1900)-(1))-(1)) NOT NULL,
    [UPDATE_BY_USER_ID]              INT        CONSTRAINT [DF_PSC_PROFILE_MISMATCH_MATRIX_UPDATE_BY_USER_ID] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_PSC_PROFILE_MISMATCH_MATRIX] PRIMARY KEY CLUSTERED ([PSC_PROFILE_MISMATCH_MATRIX_ID] ASC),
    CONSTRAINT [FK_PSC_PROFILE_MISMATCH_MATRIX_COM_ASSET_CLASS] FOREIGN KEY ([COM_ASSET_CLASS_ID]) REFERENCES [dbo].[COM_ASSET_CLASS] ([COM_ASSET_CLASS_ID]),
    CONSTRAINT [FK_PSC_PROFILE_MISMATCH_MATRIX_COM_PRODUCT_RATING] FOREIGN KEY ([COM_PRODUCT_RATING_ID]) REFERENCES [dbo].[COM_PRODUCT_RATING] ([COM_PRODUCT_RATING_ID])
);

