CREATE TABLE [dbo].[PSC_VULNERABLE_CHECKING_CRITERIA] (
    [PSC_VULNERABLE_CHECKING_CRITERIA_ID] INT          CONSTRAINT [DF_PSC_VULNERABLE_CHECKING_CRITERIA_PSC_VULNERABLE_CHECKING_CRITERIA_ID] DEFAULT ((0)) NOT NULL,
    [VARIABLE]                            VARCHAR (25) CONSTRAINT [DF_PSC_VULNERABLE_CHECKING_CRITERIA_VARIABLE] DEFAULT ('-') NOT NULL,
    [VALUE]                               INT          CONSTRAINT [DF_Table_1_VALUE_FROM] DEFAULT ((0)) NOT NULL,
    [MAX_VALUE]                           INT          CONSTRAINT [DF_Table_1_VALUE_TO] DEFAULT ((0)) NOT NULL,
    [IS_ACTIVE]                           BIT          CONSTRAINT [DF_PSC_VULNERABLE_CHECKING_CRITERIA_IS_ACTIVE] DEFAULT ((0)) NOT NULL,
    [CREATE_DATE]                         DATETIME     CONSTRAINT [DF_PSC_VULNERABLE_CHECKING_CRITERIA_CREATE_DATE] DEFAULT (((1900)-(1))-(1)) NOT NULL,
    [CREATE_BY_USER_ID]                   INT          CONSTRAINT [DF_PSC_VULNERABLE_CHECKING_CRITERIA_CREATE_BY_USER_ID] DEFAULT ((0)) NOT NULL,
    [UPDATE_DATE]                         DATETIME     CONSTRAINT [DF_PSC_VULNERABLE_CHECKING_CRITERIA_UPDATE_DATE] DEFAULT (((1900)-(1))-(1)) NOT NULL,
    [UPDATE_BY_USER_ID]                   INT          CONSTRAINT [DF_PSC_VULNERABLE_CHECKING_CRITERIA_UPDATE_BY_USER_ID] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_PSC_VULNERABLE_CHECKING_CRITERIA] PRIMARY KEY CLUSTERED ([PSC_VULNERABLE_CHECKING_CRITERIA_ID] ASC)
);

