CREATE TABLE [dbo].[PSC_FILE_TYPE] (
    [PSC_FILE_TYPE_ID] INT           NOT NULL,
    [TYPE_NAME]        VARCHAR (50)  NOT NULL,
    [DELIMITER]        VARCHAR (5)   NOT NULL,
    [DESCRIPTION]      VARCHAR (500) NOT NULL,
    CONSTRAINT [PK_PSC_FILE_TYPE] PRIMARY KEY CLUSTERED ([PSC_FILE_TYPE_ID] ASC)
);

