CREATE TABLE [dbo].[PSC_RMW_CIP] (
    [PSC_RMW_CIP_ID]              INT           IDENTITY (1, 1) NOT NULL,
    [PSC_FILE_IMPORT_ID]          INT           NOT NULL,
    [CIF]                         VARCHAR (15)  NOT NULL,
    [COM_CUSTOMER_ID]             INT           NOT NULL,
    [CUS_ID]                      INT           CONSTRAINT [DF_PSC_RMW_CIP_CUSTOMER_ID] DEFAULT ((0)) NOT NULL,
    [CUSTOMER_DOB]                DATETIME      NOT NULL,
    [COM_BRANCH_ID]               INT           CONSTRAINT [DF_PSC_RMW_CIP_COM_BRANCH_ID] DEFAULT ((0)) NOT NULL,
    [COM_CUSTOMER_SEGMENT_ID]     INT           CONSTRAINT [DF_PSC_RMW_CIP_PSC_CUSTOMER_SEGMENT_ID] DEFAULT ((0)) NOT NULL,
    [COM_CUSTOMER_RISK_RATING_ID] INT           CONSTRAINT [DF_PSC_RMW_CIP_CUSTOMER_RISK_RATING_ID] DEFAULT ((0)) NOT NULL,
    [EDUCATION_NAME]              VARCHAR (100) NOT NULL,
    [COM_RM_ID]                   INT           CONSTRAINT [DF_PSC_RMW_CIP_COM_RM_ID] DEFAULT ((0)) NOT NULL,
    [P1_Q1]                       VARCHAR (2)   NOT NULL,
    [P1_Q2]                       VARCHAR (2)   NOT NULL,
    [P1_Q3]                       VARCHAR (2)   NOT NULL,
    [P1_Q4]                       VARCHAR (2)   NOT NULL,
    [P1_Q5]                       VARCHAR (2)   NOT NULL,
    [P1_Q6]                       VARCHAR (2)   NOT NULL,
    [P1_Q7]                       VARCHAR (2)   NOT NULL,
    [Q1_EM]                       BIT           NOT NULL,
    [Q2_TOTAL_ASSET]              FLOAT (53)    NOT NULL,
    [Q2_TOTAL_LIABILITIES]        FLOAT (53)    NOT NULL,
    [Q3_1]                        BIT           NOT NULL,
    [Q3_2]                        BIT           NOT NULL,
    [Q3_3]                        BIT           NOT NULL,
    [Q3_4]                        BIT           NOT NULL,
    [Q3_5]                        BIT           NOT NULL,
    [Q3_6]                        BIT           NOT NULL,
    [Q3_7]                        BIT           NOT NULL,
    [Q3_8]                        BIT           NOT NULL,
    [Q3_9]                        BIT           NOT NULL,
    [Q3_10]                       BIT           NOT NULL,
    [Q3_11]                       BIT           NOT NULL,
    [Q3_12]                       BIT           NOT NULL,
    [Q3_13]                       BIT           NOT NULL,
    [Q4_1]                        BIT           NOT NULL,
    [Q4_2]                        BIT           NOT NULL,
    [Q4_3]                        BIT           NOT NULL,
    [Q4_4]                        BIT           NOT NULL,
    [Q4_5]                        BIT           NOT NULL,
    [Q4_6]                        BIT           NOT NULL,
    [Q5_ITH]                      FLOAT (53)    NOT NULL,
    [Q6_1]                        BIT           NOT NULL,
    [Q6_2]                        BIT           NOT NULL,
    [Q6_3]                        BIT           NOT NULL,
    [Q6_4]                        BIT           NOT NULL,
    [Q6_5]                        BIT           NOT NULL,
    [Q6_6]                        BIT           NOT NULL,
    [EXPIRY_DATE]                 DATETIME      NOT NULL,
    [CREATE_DATE]                 DATETIME      NOT NULL,
    [CREATE_BY_USER_ID]           INT           NOT NULL,
    [UPDATE_DATE]                 DATETIME      CONSTRAINT [DF_PSC_RMW_CIP_UPDATE_DATE] DEFAULT ('1900-01-01') NOT NULL,
    [UPDATE_BY_USER_ID]           INT           CONSTRAINT [DF_PSC_RMW_CIP_UPDATE_BY_USER_ID] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_PSC_RMW_CIP] PRIMARY KEY CLUSTERED ([PSC_RMW_CIP_ID] ASC),
    CONSTRAINT [FK_PSC_RMW_CIP_COM_CUSTOMER] FOREIGN KEY ([COM_CUSTOMER_ID]) REFERENCES [dbo].[COM_CUSTOMER] ([COM_CUSTOMER_ID]),
    CONSTRAINT [FK_PSC_RMW_CIP_COM_CUSTOMER_RISK_RATING] FOREIGN KEY ([COM_CUSTOMER_RISK_RATING_ID]) REFERENCES [dbo].[COM_CUSTOMER_RISK_RATING] ([COM_CUSTOMER_RISK_RATING_ID]),
    CONSTRAINT [FK_PSC_RMW_CIP_COM_CUSTOMER_SEGMENT] FOREIGN KEY ([COM_CUSTOMER_SEGMENT_ID]) REFERENCES [dbo].[COM_CUSTOMER_SEGMENT] ([COM_CUSTOMER_SEGMENT_ID]),
    CONSTRAINT [FK_PSC_RMW_CIP_COM_RM] FOREIGN KEY ([COM_RM_ID]) REFERENCES [dbo].[COM_RM] ([COM_RM_ID]),
    CONSTRAINT [FK_PSC_RMW_CIP_PSC_FILE_IMPORT] FOREIGN KEY ([PSC_FILE_IMPORT_ID]) REFERENCES [dbo].[PSC_FILE_IMPORT] ([PSC_FILE_IMPORT_ID])
);

