CREATE TABLE [dbo].[PSC_PROCESS_STATUS] (
    [PSC_PROCESS_STATUS_ID] INT           NOT NULL,
    [PROCESS_NAME]          VARCHAR (50)  NOT NULL,
    [DESCRIPTION]           VARCHAR (500) NOT NULL,
    CONSTRAINT [PK_PSC_PROCESS_STATUS] PRIMARY KEY CLUSTERED ([PSC_PROCESS_STATUS_ID] ASC)
);

