CREATE TABLE [dbo].[TMPT_SECOND_STAGING_PSC_RMW_CIP] (
    [TMPT_SECOND_STAGING_PSC_RMW_CIP_ID] INT           IDENTITY (1, 1) NOT NULL,
    [PSC_FILE_IMPORT_ID]                 INT           NOT NULL,
    [CIF]                                VARCHAR (15)  NOT NULL,
    [COM_CUSTOMER_ID]                    INT           CONSTRAINT [DF_TMPT_SECOND_STAGING_PSC_RMW_CIP_COM_CUSTOMER_ID] DEFAULT ((0)) NULL,
    [CUS_ID]                             INT           NOT NULL,
    [CUSTOMER_DOB]                       VARCHAR (50)  NOT NULL,
    [COM_BRANCH_ID]                      INT           NULL,
    [BRANCH_CODE]                        VARCHAR (30)  CONSTRAINT [DF_TMPT_SECOND_STAGING_PSC_RMW_CIP_BRANCH_CODE] DEFAULT ('-') NOT NULL,
    [BRANCH_NAME]                        VARCHAR (100) CONSTRAINT [DF_TMPT_SECOND_STAGING_PSC_RMW_CIP_BRANCH_NAME] DEFAULT ('-') NOT NULL,
    [COM_CUSTOMER_SEGMENT_ID]            INT           NOT NULL,
    [COM_CUSTOMER_RISK_RATING_ID]        INT           NOT NULL,
    [EDUCATION_NAME]                     VARCHAR (100) NOT NULL,
    [COM_RM_ID]                          INT           NOT NULL,
    [P1_Q1]                              VARCHAR (2)   NOT NULL,
    [P1_Q2]                              VARCHAR (2)   NOT NULL,
    [P1_Q3]                              VARCHAR (2)   NOT NULL,
    [P1_Q4]                              VARCHAR (2)   NOT NULL,
    [P1_Q5]                              VARCHAR (2)   NOT NULL,
    [P1_Q6]                              VARCHAR (2)   NOT NULL,
    [P1_Q7]                              VARCHAR (2)   NOT NULL,
    [Q1_EM]                              BIT           NOT NULL,
    [Q2_TOTAL_ASSET]                     FLOAT (53)    NOT NULL,
    [Q2_TOTAL_LIABILITIES]               FLOAT (53)    NOT NULL,
    [Q3_1]                               BIT           NOT NULL,
    [Q3_2]                               BIT           NOT NULL,
    [Q3_3]                               BIT           NOT NULL,
    [Q3_4]                               BIT           NOT NULL,
    [Q3_5]                               BIT           NOT NULL,
    [Q3_6]                               BIT           NOT NULL,
    [Q3_7]                               BIT           NOT NULL,
    [Q3_8]                               BIT           NOT NULL,
    [Q3_9]                               BIT           NOT NULL,
    [Q3_10]                              BIT           NOT NULL,
    [Q3_11]                              BIT           NOT NULL,
    [Q3_12]                              BIT           NOT NULL,
    [Q3_13]                              BIT           NOT NULL,
    [Q4_1]                               BIT           NOT NULL,
    [Q4_2]                               BIT           NOT NULL,
    [Q4_3]                               BIT           NOT NULL,
    [Q4_4]                               BIT           NOT NULL,
    [Q4_5]                               BIT           NOT NULL,
    [Q4_6]                               BIT           NOT NULL,
    [Q5_ITH]                             FLOAT (53)    NOT NULL,
    [Q6_1]                               BIT           NOT NULL,
    [Q6_2]                               BIT           NOT NULL,
    [Q6_3]                               BIT           NOT NULL,
    [Q6_4]                               BIT           NOT NULL,
    [Q6_5]                               BIT           NOT NULL,
    [Q6_6]                               BIT           NOT NULL,
    [IS_VALID]                           BIT           NOT NULL,
    [INVALID_REMARK]                     VARCHAR (500) NOT NULL,
    [CREATE_DATE]                        VARCHAR (50)  NOT NULL,
    CONSTRAINT [PK_TMPT_SECOND_STAGING_PSC_RMW_CIP] PRIMARY KEY CLUSTERED ([TMPT_SECOND_STAGING_PSC_RMW_CIP_ID] ASC),
    CONSTRAINT [FK_TMPT_SECOND_STAGING_PSC_RMW_CIP_PSC_FILE_IMPORT] FOREIGN KEY ([PSC_FILE_IMPORT_ID]) REFERENCES [dbo].[PSC_FILE_IMPORT] ([PSC_FILE_IMPORT_ID])
);

